version: 2.1 # use CircleCI 2.0
orbs:
  slack: circleci/slack@3.2.0
jobs: # basic units of work in a run
  test:
    # working_directory: /tmp/workspace
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: golang:1.13-alpine
    environment: # environment variables for the build itself
      TEST_RESULTS: test-results # path to where test results will be saved
    steps: # steps that comprise the `build` job
      # - slack/notify:
      #     message: "This is a custom message notification"
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run:
          name: Run unit tests
          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            echo $CIRCLE_WORKING_DIRECTORY
            go test -v ./...
      - store_artifacts: # upload test summary for display in Artifacts
          path: test-results
          destination: raw-test-output
      - store_test_results: # upload test results for display in Test Summary
          path: test-results

  build:
    machine: true
    environment: # environment variables for the build itself
      TEST_RESULTS: test-results # path to where test results will be saved
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run:
          name: Build Docker Image
          command: |
            ls -la
            docker build -t hellow-world:latest .
            docker save -o test-results/hellow-world.tar hellow-world:latest
      - persist_to_workspace:
          root: .
          paths:
            - test-results
      - store_artifacts: # upload test summary for display in Artifacts
          path: test-results
          destination: raw-test-output

  deploy:
    machine: true
    steps: # steps that comprise the `build` job
      - attach_workspace:
          at: .
      - run:
          name: Run a Service
          command: |
            docker load --input test-results/hellow-world.tar
            docker run --name hellow-world hellow-world:latest

  test_context:
    machine: true
    steps:
      - run:
          name: Test context
          command: |
            echo $SLACK_WEBHOOK


workflows:
  version: 2
  build-workflow:
    jobs:
      # - test_context:
      #     context: secrets
      - test
      - build
      - slack/approval-notification:
          message: Pending approval
          requires:
            - build
      - approval:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approval

